### ISSUE TITLE
🤗 Have a demo on Hugging Face for OWL-CON checkpoint

### ISSUE THREAD

**Issue by merveenoyan** [Hritikbansal/videocon#1]
Hello 👋  Great work! I thought it would be nice to put up a demo for your model (using Gradio) hosted on Hugging Face Spaces.

**Comment by Hritikbansal** [comment]
Hi @merveenoyan , 

Thank you for your comments and great idea!

Sure, I can take a look at this in a few days.

**Comment by merveenoyan** [comment]
@Hritikbansal great! Also I'd love to offer my help in case you have any questions.

**Comment by Hritikbansal** [comment]
Hi @merveenoyan , thanks for pushing us to create a HF demo! 

Here is the link to the public demo: https://huggingface.co/spaces/hbXNov/owl-con-demo

I have also opened a discussion for GPU community grant since I don't have much personal funds. It would be helpful if it can be approved!
